# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R92HcjVd0wkjDmXq_TShklU9dbBvdTFJ

Day 02: Explicit schemas and file ingestion

1.Why can schema inference be risky for customer and product identifiers?

ANS::Schema inference may convert identifiers into numeric types. This can remove leading zeros or change formatting. For example, customer ID 00123 may become 123, causing incorrect joins and data quality issues.

2.What do StructType and StructField represent?
"""

# StructType: Defines the complete schema of a DataFrame.
# StructField: Defines an individual column, including:
# Column name
# Data type
# Nullable property
from pyspark.sql.types import *
schema=StructType([   StructField("customer_id", StringType(), True),
    StructField("city", StringType(), True)])

"""3.What does nullable mean in a Spark schema?"""

# nullable=True means the column can contain NULL values.

# nullable=False means Spark expects the column to contain a value, although it does not fully enforce data quality during all file reads.
schema=StructType([   StructField("customer_id", StringType(), True),
    StructField("city", StringType(), True)])

"""4.Which type should represent quantity, and why?"""

# IntegerType are represent quantity because quantities are whole numbers
StructField("quantity", IntegerType(), True)

"""5.Why use a decimal type for retail prices?

Floating-point types can introduce rounding errors.

Example:

0.1 + 0.2 = 0.30000000000000004

Decimal provides precise financial calculations.

6.How do DateType and TimestampType differ?
"""

# Type	           Stores
# DateType	       Date only (YYYY-MM-DD)
# TimestampType	    Date + Time

"""7.What does the CSV header option control?

The header option tells Spark whether the first row contains column names.

Example:

spark.read.option("header", "true").csv(path)

8. What is the difference between a blank field and a quoted empty string?
"""

#Blank field → may be interpreted as NULL.
#Quoted empty string ("") → empty string value (""), not necessarily NULL.

"""9.What does PERMISSIVE parsing attempt to preserve?

PERMISSIVE mode attempts to load as much data as possible.

Malformed records are retained and valid columns are still parsed.

10. Why do file streams normally require an explicit schema?

Streaming data must be processed continuously.

Schema inference would require repeatedly scanning files, which is expensive and unreliable.

Benefits of explicit schema:

Faster startup
Consistent structure
Better performance
Predictable processing

11.Define and use a complete schema for customers.csv.
"""

from pyspark.sql.types import *
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("pysparkAssignment") \
    .getOrCreate()
customers_schema=StructType([
    StructField("customer_id",StringType(), True),
    StructField("name", StringType(), True),
    StructField("email", StringType(), True),
    StructField("city", StringType(), True),
    StructField("signup_date", DateType(), True),
    StructField("updated_at", TimestampType(), True)
])
customers_df=(
    spark.read.format("csv")
    .option("header", "true")
    .schema(customers_schema)
    .load("/content/customers (1).csv")
)
customers_df.show()

"""12.Define a complete order_items schema with decimal prices and discounts."""

from pyspark.sql.types import *

order_items_schema = StructType([
    StructField("line_id", StringType(), True),
    StructField("order_id", StringType(), True),
    StructField("product_id", StringType(), True),
    StructField("quantity", IntegerType(), True),
    StructField("unit_price", DecimalType(10,2), True),
    StructField("discount_pct", DecimalType(5,2), True)
])

order_items_df = (
    spark.read
    .option("header","true")
    .schema(order_items_schema)
    .csv("/content/order_items (1).csv")
)

order_items_df.printSchema()

"""13.Read orders with order_ts parsed as a timestamp in UTC."""

spark.conf.set("spark.sql.session.timeZone","UTC")

from pyspark.sql.types import *

orders_schema = StructType([
    StructField("order_id", StringType(), True),
    StructField("customer_id", StringType(), True),
    StructField("store_id", StringType(), True),
    StructField("order_ts", TimestampType(), True),
    StructField("status", StringType(), True),
    StructField("channel", StringType(), True)
])

orders_df = (
    spark.read
    .option("header","true")
    .schema(orders_schema)
    .csv("/content/orders (1).csv")
)

orders_df.printSchema()

"""14.Compare inferred and explicit schemas for the same CSV file."""

# Explicit schema guarantees customer_id remains String.
# Explicit schema is faster because Spark does not scan data for type inference.

infer_schema=(
    spark.read.format("csv")
    .option("header","true")
    .option("inferSchema",'true')
    .load("/content/customers (1).csv")
)

explict_schema=(
    spark.read.format("csv")
    .option("header",'true')
    .schema(customers_schema)
    .load("/content/customers (1).csv")
)

print("Inferred Schema:")
infer_schema.printSchema()
print("Explicit Schema:")
explict_schema.printSchema()

"""15.Read a CSV fixture containing a quoted comma in a customer name"""

from pyspark.sql.types import StructType, StructField, StringType

# Clear Spark's catalog cache to avoid conflicting schema issues
spark.catalog.clearCache()

# Define the schema matching the structure we want to read safely
schema = StructType([
    StructField("customer_id", StringType(), True),
    StructField("name", StringType(), True),
    StructField("email", StringType(), True),
    StructField("city", StringType(), True),
    StructField("signup_date", StringType(), True),
    StructField("updated_at", StringType(), True)
])

df = (
    spark.read
    .option("header", "true")
    .option("quote", "\"")
    .option("escape", "\"")
    .schema(schema)
    .csv("/content/customers (1).csv")
)

df.select("customer_id", "name").show(truncate=False)

"""16.Read a header-only CSV with an explicit schema and verify zero rows."""

from pyspark.sql.types import *

schema = StructType([
    StructField("customer_id", StringType(), True),
    StructField("name", StringType(), True),
    StructField("email", StringType(), True)
])

df = (
    spark.read
    .option("header", "true")
    .schema(schema)
    .csv("/content/customers (1).csv")
)

df.printSchema()
print("Row Count =", df.count())
df.show()

"""17.Create a malformed numeric fixture and inspect PERMISSIVE output."""

from pyspark.sql.types import *

schema = StructType([
    StructField("order_id", StringType(), True),
    StructField("quantity", IntegerType(), True)
])

df = (
    spark.read
    .option("header", "true")
    .option("mode", "PERMISSIVE")
    .schema(schema)
    .csv("/content/order_items (1).csv")
)

df.show()

"""18.Compare DROPMALFORMED and FAILFAST on that fixture using an action."""

#dropmalformed
drop_df = (
    spark.read
    .option("header", "true")
    .option("mode", "DROPMALFORMED")
    .schema(schema)
    .csv("/content/order_items (1).csv")
)

drop_df.show()

#failfast
fail_df = (
    spark.read
    .option("header", "true")
    .option("mode", "FAILFAST")
    .schema(schema)
    .csv("/content/order_items (1).csv")
)

fail_df.count()

"""19. Add source filename and ingestion timestamp audit columns"""

from pyspark.sql.functions import input_file_name, current_timestamp

audit_df = (
    customers_df
    .withColumn("source_file", input_file_name())
    .withColumn("ingestion_time", current_timestamp())
)

audit_df.show(truncate=False)

"""20. Read one event archive file using the supplied nested event_schema"""

from examples.schemas import event_schema

events_df = (
    spark.read
    .schema(event_schema)
    .json("/content/order_items (1).csv")
)

events_df.printSchema()
events_df.show(truncate=False)

"""21.Preserve malformed CSV evidence using a configured corrupt-record column."""

with open("bad_data.csv", "w") as f:
    f.write(
        "order_id,quantity\n"
        "O001,5\n"
        "O002,ABC\n"
        "O003,10"
    )

    from pyspark.sql.types import *

schema = StructType([
    StructField("order_id", StringType(), True),
    StructField("quantity", IntegerType(), True),
    StructField("_corrupt_record", StringType(), True)
])

df = (
    spark.read
    .option("header", "true")
    .option("mode", "PERMISSIVE")
    .option("columnNameOfCorruptRecord", "_corrupt_record")
    .schema(schema)
    .csv("bad_data.csv")
)

df.show(truncate=False)

"""22.Explain why fewer or extra CSV tokens are not always classified as corrupt records

Answer

Spark CSV parsing is flexible.

Example:

Expected schema:

id,name,city

Input:

1,John

Spark may simply assign:

id=1
name=John
city=NULL

Similarly:

1,John,Delhi,ExtraValue

may ignore the extra token instead of marking the record as corrupt.

Therefore fewer or extra tokens do not always create corrupt records; Spark may fill missing values with NULL or ignore extra values depending on configuration.

23.Demonstrate how column pruning can affect CSV corruption detectio

answer::

Because Spark reads only required columns, corruption in unused columns may not be detected. This behavior is called column pruning.

24.Compare missing columns, reordered columns, and incompatible types during ingestion.
"""

# Scenario	                Result
# Missing Column	      Spark fills NULL values
# Reordered Columns	     Data may go into wrong columns if schema/header mismatch
# Incompatible Type	      Value becomes NULL or parsing error

"""25.Design a contract that distinguishes parsing failures from business-rule failures"""

# answers::

# Design

# Parsing Failure

# Examples:

# ABC in Integer column
# Invalid timestamp
# Malformed CSV row

# Store in:

# parse_error_reason

# Business Rule Failure

# Examples:

# quantity < 0
# discount > 100
# price < 0

# Store in:

# business_error_reason
# Output
# record_status
# PARSE_FAILED
# BUSINESS_FAILED
# VALID

# This separates ingestion problems from business validation problems.

"""26.Explain why nullable=False is not a complete data-quality enforcement strategy.

Answer

nullable=False only defines schema expectations.

It does not guarantee:

Valid email format
Positive quantity
Correct business keys
Unique IDs

27.Preserve an identifier with leading zeros through read and write.
"""

schema = StructType([
    StructField("customer_id", StringType(), True)
])

"""28.Create a decimal-overflow fixture and record parsing behavior under your configuration."""

schema = StructType([
    StructField("amount", DecimalType(5,2), True)
])

"""29.Design ingestion that retains raw text for rows that cannot be typed safely.

Stage 1:

Read everything as StringType.

raw_df = spark.read.option("header","true").csv(path)

Stage 2:

Create typed columns.

typed_df = raw_df.withColumn(
    "quantity_int",
    col("quantity").cast("int")
)

Stage 3:

Invalid records:

invalid_df = typed_df.filter(
    col("quantity_int").isNull()
)

30.Write a reusable reader with schema, format, audit columns, and parse-mode arguments.
"""

from pyspark.sql.functions import (
    input_file_name,
    current_timestamp
)

def read_data(
        path,
        schema,
        file_format="csv",
        mode="PERMISSIVE"):

    df = (
        spark.read
        .format(file_format)
        .option("header", "true")
        .option("mode", mode)
        .schema(schema)
        .load(path)
    )

    return (
        df
        .withColumn(
            "source_file",
            input_file_name()
        )
        .withColumn(
            "ingestion_time",
            current_timestamp()
        )
    )

customers_df = read_data(
    path="/content/customers (1).csv",
    schema=customers_schema,
    file_format="csv",
    mode="PERMISSIVE"
)
